<?php
// auto-generated by sfPropelCrud
// date: 2009/08/15 10:46:50
?>
<?php

/**
 * addresses actions.
 *
 * @package    coscupdemo
 * @subpackage addresses
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class addressesActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('addresses', 'list');
  }

  public function executeList()
  {
    $this->ab_addressess = AbAddressesPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->ab_addresses = AbAddressesPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->ab_addresses);
  }

  public function executeCreate()
  {
    $this->ab_addresses = new AbAddresses();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->ab_addresses = AbAddressesPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->ab_addresses);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $ab_addresses = new AbAddresses();
    }
    else
    {
      $ab_addresses = AbAddressesPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($ab_addresses);
    }

    $ab_addresses->setId($this->getRequestParameter('id'));
    $ab_addresses->setFullname($this->getRequestParameter('fullname'));
    $ab_addresses->setEmailAddress($this->getRequestParameter('email_address'));
    $ab_addresses->setHomeAddress($this->getRequestParameter('home_address'));
    $ab_addresses->setPhone($this->getRequestParameter('phone'));
    $ab_addresses->setAbCategoryId($this->getRequestParameter('ab_category_id') ? $this->getRequestParameter('ab_category_id') : null);

    $ab_addresses->save();

    return $this->redirect('addresses/show?id='.$ab_addresses->getId());
  }

  public function executeDelete()
  {
    $ab_addresses = AbAddressesPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($ab_addresses);

    $ab_addresses->delete();

    return $this->redirect('addresses/list');
  }
}
