<?php
// auto-generated by sfPropelCrud
// date: 2009/08/15 10:46:50
?>
<?php use_helper('Object') ?>

<?php echo form_tag('addresses/update') ?>

<?php echo object_input_hidden_tag($ab_addresses, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Fullname*:</th>
  <td><?php echo object_input_tag($ab_addresses, 'getFullname', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Email address*:</th>
  <td><?php echo object_input_tag($ab_addresses, 'getEmailAddress', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Home address:</th>
  <td><?php echo object_input_tag($ab_addresses, 'getHomeAddress', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Phone:</th>
  <td><?php echo object_input_tag($ab_addresses, 'getPhone', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Ab category*:</th>
  <td><?php echo object_select_tag($ab_addresses, 'getAbCategoryId', array (
  'related_class' => 'AbCategory',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($ab_addresses->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'addresses/delete?id='.$ab_addresses->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'addresses/show?id='.$ab_addresses->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'addresses/list') ?>
<?php endif; ?>
</form>
