<?php
// auto-generated by sfPropelCrud
// date: 2009/08/15 10:46:50
?>
<h1>List Address</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Fullname</th>
  <th>Email address</th>
  <th>Home address</th>
  <th>Phone</th>
  <th>Ab category</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($ab_addressess as $ab_addresses): ?>
<tr>
    <td><?php echo link_to($ab_addresses->getId(), 'addresses/show?id='.$ab_addresses->getId()) ?></td>
      <td><?php echo $ab_addresses->getFullname() ?></td>
      <td><?php echo $ab_addresses->getEmailAddress() ?></td>
      <td><?php echo $ab_addresses->getHomeAddress() ?></td>
      <td><?php echo $ab_addresses->getPhone() ?></td>
      <td><?php echo $ab_addresses->getAbCategory()->getCatName() ?></td>
      <td><?php echo $ab_addresses->getCreatedAt() ?></td>
      <td><?php echo $ab_addresses->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'addresses/create') ?>
