<?php
// auto-generated by sfPropelCrud
// date: 2009/08/15 10:46:50
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $ab_addresses->getId() ?></td>
</tr>
<tr>
<th>Fullname: </th>
<td><?php echo $ab_addresses->getFullname() ?></td>
</tr>
<tr>
<th>Email address: </th>
<td><?php echo $ab_addresses->getEmailAddress() ?></td>
</tr>
<tr>
<th>Home address: </th>
<td><?php echo $ab_addresses->getHomeAddress() ?></td>
</tr>
<tr>
<th>Phone: </th>
<td><?php echo $ab_addresses->getPhone() ?></td>
</tr>
<tr>
<th>Ab category: </th>
<td><?php echo $ab_addresses->getAbCategoryId() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $ab_addresses->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $ab_addresses->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'addresses/edit?id='.$ab_addresses->getId()) ?>
&nbsp;<?php echo link_to('list', 'addresses/list') ?>
