<?php
// auto-generated by sfPropelCrud
// date: 2009/08/15 10:47:44
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $ab_category->getId() ?></td>
</tr>
<tr>
<th>Cat name: </th>
<td><?php echo $ab_category->getCatName() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $ab_category->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $ab_category->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'category/edit?id='.$ab_category->getId()) ?>
&nbsp;<?php echo link_to('list', 'category/list') ?>
