<?php
// auto-generated by sfPropelCrud
// date: 2009/08/15 10:47:44
?>
<?php

/**
 * category actions.
 *
 * @package    coscupdemo
 * @subpackage category
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class categoryActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('category', 'list');
  }

  public function executeList()
  {
    $this->ab_categorys = AbCategoryPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->ab_category = AbCategoryPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->ab_category);
  }

  public function executeCreate()
  {
    $this->ab_category = new AbCategory();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->ab_category = AbCategoryPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->ab_category);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $ab_category = new AbCategory();
    }
    else
    {
      $ab_category = AbCategoryPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($ab_category);
    }

    $ab_category->setId($this->getRequestParameter('id'));
    $ab_category->setCatName($this->getRequestParameter('cat_name'));

    $ab_category->save();

    return $this->redirect('category/show?id='.$ab_category->getId());
  }

  public function executeDelete()
  {
    $ab_category = AbCategoryPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($ab_category);

    $ab_category->delete();

    return $this->redirect('category/list');
  }
}
