<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/08/15 10:45:03

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'pgsql://coscupdemo:demo@localhost/coscupdemo',
), 'propel');
$this->databases['propel'] = $database;
